RagnarokWebsite/Models/AttendeeViewModel.cs
using RagnarokWebsite.Data.Context;
using RagnarokWebsite.Data.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace RagnarokWebsite.Models
{
    public class AttendeeViewModel
    {
        private RagnarokContext db = new RagnarokContext();

        [Key]
        [HiddenInput(DisplayValue = false)]
        public int ParticipantId { get; set; }

        public string CampName { get; set; }

        public List<SelectListItem> CampOptions { get; set; }
        [Required]
        public string CampId { get; set; }

        [DataType(DataType.Text)]
        public int TagNumber { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string FirstName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public DateTime DOB { get; set; }

        public bool IsMinor { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string CharacterName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string ChapterName { get; set; }

        [DataType(DataType.Text)]
        public string UnitName { get; set; }

        public DateTime EventYear { get; set; }
        public DateTime DateSigned { get; set; }

        public List<SelectListItem> StatusOptions { get; set; }
        public string Status { get; set; }

        public DateTime RegistrationDate { get; set; }
        public DateTime ArrivalDate { get; set; }

        public bool IsMerchant { get; set; }
        public bool VolunteerTroll { get; set; }
        public bool VolunteerSafety { get; set; }
        public bool VolunteerMedic { get; set; }
        public bool VolunteerDay { get; set; }
        public bool VolunteerNight { get; set; }
        public bool VolunteerWeapon { get; set; }
        public bool VolunteerRagU { get; set; }

        [DataType(DataType.Text)]
        public int MinorParentTagNumber { get; set; }

        public bool ReplacementTag { get; set; }











        public AttendeeViewModel()
        {

        }

        public AttendeeViewModel(Participant participant)
        {
            ParticipantId = participant.ParticipantId;
            FirstName = participant.FirstName;
            LastName = participant.LastName;
            DOB = participant.DOB;
            IsMinor = participant.IsMinor == "Y" ? true : false;
            CampName = participant.Camp.Name;
            CharacterName = participant.CharacterName;
            Status = participant.Status;
            IsMerchant = participant.IsMerchant == "Y" ? true : false;
        }
    }
}

RagnarokWebsite/Models/AttendeesViewModel.cs
using PagedList;
using RagnarokWebsite.Extensions;
using System.Collections.Generic;
using System.Web.Mvc;

namespace RagnarokWebsite.Models
{
    public class AttendeesViewModel
    {
        public int Page { get; set; }
        public int PageLength { get; set; }

        public List<SelectListItem> Options { get; set; }
        public string Year { get; set; }

        public string Search { get; set; }

        public IPagedList<AttendeeViewModel> Attendees { get; set; }
        
        public AttendeesViewModel()
        {
            Options = DateExtensions.GetDateOptions();
        }
    }
}

RagnarokWebsite/Areas/Administration/Controllers/AttendeesController.cs
using PagedList;
using RagnarokWebsite.Controllers;
using RagnarokWebsite.Data.Context;
using RagnarokWebsite.Models;
using RagnarokWebsite.Security.Constants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RagnarokWebsite.Areas.Administration.Controllers
{
    [Authorize]
    public class AttendeesController : RagnarokController
    {
        private RagnarokContext db = new RagnarokContext();

        // GET: Administration/Attendees
        public ActionResult Index(int? page, int? pageLength, int? year, string search = "")
        {
            if (!ValidateCredentials(PermissionConstants.VIEW_ATTENDEE_ADMINISTRATION))
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            int pageSize = (pageLength ?? 25);
            int pageNumber = (page ?? 1);
            int pageYear = (year ?? 2020);

            AttendeesViewModel avm = new AttendeesViewModel();
            var attendees = db.Participants.Where(p => p.EventYear.Year == pageYear).Select(participant => new AttendeeViewModel
            {
                ParticipantId = participant.ParticipantId,
                FirstName = participant.FirstName,
                LastName = participant.LastName,
                DOB = participant.DOB,
                IsMinor = participant.IsMinor == "Y" ? true : false,
                CampName = participant.Camp.Name,
                CharacterName = participant.CharacterName,
                Status = participant.Status,
                IsMerchant = participant.IsMerchant == "Y" ? true : false
            });

            if (!string.IsNullOrEmpty(search))
            {
                attendees = attendees.Where(p => p.FirstName.ToLower().Contains(search.ToLower()) || p.LastName.ToLower().Contains(search.ToLower()) || 
                    p.CharacterName.ToLower().Contains(search.ToLower()) || p.CampName.ToLower().Contains(search.ToLower()));
            }

            attendees = attendees.OrderBy(c => c.LastName).ThenBy(c => c.FirstName);

            avm.Attendees = attendees.ToPagedList(pageNumber, pageSize);
            avm.Page = pageNumber;

            if (avm.Attendees.PageNumber > avm.Attendees.PageCount)
            {
                avm.Attendees = attendees.ToPagedList(1, pageSize);
                avm.Page = 1;
            }

            avm.PageLength = pageSize;
            avm.Year = pageYear.ToString();

            return View(avm);
        }
    }
}

RagnarokWebsite/Areas/Administration/Views/Attendees/Create.cshtml
@model RagnarokWebsite.Models.AttendeeViewModel

@{
    /**/

    ViewBag.Title = "Ragnarok > Camp Administration - Add New Camp";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12"><h2>Camp Administration - Add New Camp</h2></div>
</div>


@using (Html.BeginForm())
{
    <div class="row">
        @Html.AntiForgeryToken()

        <div class="col-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Location</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "" } })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Year</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.DropDownListFor(model => Model.Year, Model.Options)
        </div>
    </div>

    <div class="row">
        <div class="col-12 pt-2">
            <h3>Camp Master Information</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">First Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMFirstName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMFirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Last Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMLastName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMLastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Character Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMCharacterName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMCharacterName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Email</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMEmail, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-12 pt-2">
            <input type="submit" value="Add Camp" class="btn btn-success centerButton" />
        </div>
    </div>
}

<div class="row">
    <div class="col-12 pb-2 pb-2">
        @Html.ActionLink("Back to Camps", "Index")
    </div>
</div>

RagnarokWebsite/Areas/Administration/Views/Attendees/Index.cshtml
@model RagnarokWebsite.Models.AttendeesViewModel

@using PagedList.Mvc;
@using RagnarokWebsite.Security.Constants;

@{
    ViewBag.Title = "Ragnarok > Attendee Administration";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-4 col-xs-12"><h1>Attendee Administration</h1></div>
    <div class="col-md-8 col-xs-12 right headerRight text-right">
        @if (CheckPermission(PermissionConstants.CREATE_NEW_ATTENDEES))
        {
            @Html.ActionLink("Add New Attendee", "Create")
        }
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-xs-12 pb-2">
        @using (Html.BeginForm("Index", "Attendees", FormMethod.Get))
        {
            @Html.HiddenFor(model => Model.Page)
            @Html.HiddenFor(model => Model.Year)
            @:Show
            <select id="PageLength" name="PageLength" onchange="form.submit();">
                @if (Model.PageLength == 10)
                {
                    <option value="10" selected>10</option>
                }
                else
                {
                    <option value="10">10</option>
                }
                @if (Model.PageLength == 25)
                {
                    <option value="25" selected>25</option>
                }
                else
                {
                    <option value="25">25</option>
                }
                @if (Model.PageLength == 50)
                {
                    <option value="50" selected>50</option>
                }
                else
                {
                    <option value="50">50</option>
                }
                @if (Model.PageLength == 100)
                {
                    <option value="100" selected>100</option>
                }
                else
                {
                    <option value="100">100</option>
                }
            </select>@: entries
        }
    </div>
    <div class="col-md-8 col-xs-12 pb-2 text-right">
        @using (Html.BeginForm("Index", "Attendees", FormMethod.Get))
        {
            @Html.HiddenFor(model => Model.Page)
            @Html.HiddenFor(model => Model.PageLength)
            @Html.EditorFor(model => Model.Search)
            <input type="submit" class="btn btn-sm btn-success" value="Search" />@:&nbsp;| &nbsp;
            @:Year: @Html.DropDownListFor(model => Model.Year, Model.Options, new { @onchange = @"form.submit();" })
        }

        @using (Html.BeginForm("Index", "Attendees", FormMethod.Get))
        {
            @Html.HiddenFor(model => Model.Page)
            @Html.HiddenFor(model => Model.PageLength)

        }
    </div>
</div>
<div class="row">
    <div class="col-12">
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th>Last Name</th>
                    <th>First Name</th>
                    <th>DOB</th>
                    <th>Minor</th>
                    <th>Camp</th>
                    <th>Character Name</th>
                    <th>Merchant</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var attendee in Model.Attendees)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => attendee.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => attendee.FirstName)
                        </td>
                        <td>
                            @{ 
                                string dateValue = attendee.DOB.ToString("MM/dd/yyyy");
                            }
                            @Html.DisplayFor(modelItem => dateValue)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => attendee.IsMinor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => attendee.CampName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => attendee.CharacterName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => attendee.IsMerchant)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => attendee.Status)
                        </td>
                        <td class="text-right">
                            @if (CheckPermission(PermissionConstants.EDIT_EXISTING_ATTENDEES))
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = attendee.ParticipantId })
                            }
                            @if (CheckPermission(PermissionConstants.DELETE_ATTENDEES))
                            {
                                if (CheckPermission(PermissionConstants.EDIT_EXISTING_ATTENDEES))
                                {
                                    <span> | </span>
                                }

                                using (Html.BeginForm("Delete", "Attendees", FormMethod.Post, new { @class = "btn-link deleteButton" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.Hidden("participantId", attendee.ParticipantId)
                                    <input type="submit" class="btn-link" value="Delete" onclick="return confirm('Are you sure you wish to remove this attendee?')" />
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4 col-xs-12 pt-2 pb-2">
        Showing @Model.Attendees.FirstItemOnPage to @Model.Attendees.LastItemOnPage of @Model.Attendees.TotalItemCount Records
    </div>
    <div class="col-md-8 col-xs-12 pt-2 pb-2 text-center">
        @Html.PagedListPager(Model.Attendees, page => Url.Action("Index", new { page,
            PageLength = Model.PageLength,
            Year = Model.Year
        }), new PagedListRenderOptions { LinkToFirstPageFormat = "First", LinkToPreviousPageFormat = "Previous", LinkToNextPageFormat = "Next", LinkToLastPageFormat = "Last",
            DisplayLinkToFirstPage = PagedListDisplayMode.Always, DisplayLinkToPreviousPage = PagedListDisplayMode.Always, DisplayLinkToNextPage = PagedListDisplayMode.Always,
            DisplayLinkToLastPage = PagedListDisplayMode.Always, DisplayEllipsesWhenNotShowingAllPageNumbers = true, MaximumPageNumbersToDisplay = 10 })
    </div>
</div>