RagnarokWebsite/Models/CampViewModel.cs
using RagnarokWebsite.Data.Context;
using RagnarokWebsite.Data.Models;
using RagnarokWebsite.Extensions;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace RagnarokWebsite.Models
{
    public class CampViewModel
    {
        private RagnarokContext db = new RagnarokContext();
        
        [Key]
        [HiddenInput(DisplayValue = false)]
        public int CampId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        public string Location { get; set; }
        
        public List<SelectListItem> Options { get; set; }
        public string Year { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int CampMasterId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string CMFirstName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string CMLastName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string CMCharacterName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string CMEmail { get; set; }

        public int NumRegistrations { get; set; }

        public CampViewModel()
        {
            PopulateOptions();

            Year = "2020";
            NumRegistrations = 0;
        }

        public CampViewModel(Camp camp)
        {
            PopulateOptions();

            CampId = camp.CampId;
            Name = camp.Name;
            Location = camp.Location;
            Year = camp.Year.ToString();

            CampMasterId = camp.CampMaster.CampMasterId;
            CMFirstName = camp.CampMaster.FirstName;
            CMLastName = camp.CampMaster.LastName;
            CMCharacterName = camp.CampMaster.CharacterName;
            CMEmail = camp.CampMaster.Email;

            NumRegistrations = camp.Participants.Count;
        }

        private void PopulateOptions()
        {
            Options = DateExtensions.GetDateOptions();
        }
    }
}

RagnarokWebsite/Models/CampsViewModel.cs
using PagedList;
using RagnarokWebsite.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RagnarokWebsite.Models
{
    public class CampsViewModel
    {
        public int Page { get; set; }
        public int PageLength { get; set; }

        public List<SelectListItem> Options { get; set; }
        public string Year { get; set; }

        public IPagedList<Camp> Camps { get; set; }

        public CampsViewModel()
        {
            Options = new List<SelectListItem>();

            Options.Add(new System.Web.Mvc.SelectListItem
            {
                Value = "2017",
                Text = "2017"
            });
            Options.Add(new System.Web.Mvc.SelectListItem
            {
                Value = "2018",
                Text = "2018"
            });
            Options.Add(new System.Web.Mvc.SelectListItem
            {
                Value = "2019",
                Text = "2019"
            });
            Options.Add(new System.Web.Mvc.SelectListItem
            {
                Value = "2020",
                Text = "2020",
                Selected = true
            });
        }
    }
}

RagnarokWebsite/Areas/Administration/Controllers/CampsController.cs
using PagedList;
using RagnarokWebsite.Constants;
using RagnarokWebsite.Controllers;
using RagnarokWebsite.Data.Context;
using RagnarokWebsite.Data.Models;
using RagnarokWebsite.Models;
using RagnarokWebsite.Security.Constants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RagnarokWebsite.Areas.Administration.Controllers
{
    [Authorize]
    public class CampsController : RagnarokController
    {
        private RagnarokContext db = new RagnarokContext();

        // GET: Administration/Camps
        public ActionResult Index(int? page, int? pageLength, int? year)
        {
            if (!ValidateCredentials(PermissionConstants.VIEW_CAMP_ADMINISTRATION))
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            int pageSize = (pageLength ?? 25);
            int pageNumber = (page ?? 1);
            int pageYear = (year ?? 2020);

            CampsViewModel cvm = new CampsViewModel();
            var camps = db.Camps.Where(c => c.Year == pageYear).Select(camp => new CampViewModel
            {
                CampId = camp.CampId,
                CampMasterId = camp.CampMasterId,
                Name = camp.Name,
                Location = camp.Location,
                Year = camp.Year.ToString(),
                CMCharacterName = camp.CampMaster.CharacterName, 
                NumRegistrations = camp.Participants.Where(p => p.Status == "Paid" || p.Status == "Checked In").Count()
            }).OrderBy(c => c.Name);

            cvm.Camps = camps.ToPagedList(pageNumber, pageSize);
            cvm.Page = pageNumber;

            if (cvm.Camps.PageNumber > cvm.Camps.PageCount)
            {
                cvm.Camps = camps.ToPagedList(1, pageSize);
                cvm.Page = 1;
            }

            cvm.PageLength = pageSize;
            cvm.Year = pageYear.ToString();

            return View(cvm);
        }

        // GET: Administration/Camps/Create
        public ActionResult Create()
        {
            if (!ValidateCredentials(PermissionConstants.CREATE_NEW_CAMPS))
            {
                return RedirectToAction("Index");
            }

            return View(new CampViewModel());
        }

        [HttpPost]
        public ActionResult Create(FormCollection formCollection)
        {
            if (!ValidateCredentials(PermissionConstants.CREATE_NEW_CAMPS))
            {
                return RedirectToAction("Index");
            }

            try
            {
                Camp newCamp = new Camp
                {
                    CampId = 0, 
                    Name = formCollection["Name"], 
                    Location = formCollection["Location"], 
                    Year = Convert.ToInt16(formCollection["Year"]), 
                    CampMaster = new CampMaster
                    {
                        CampMasterId = 0, 
                        FirstName = formCollection["CMFirstName"], 
                        LastName = formCollection["CMLastName"], 
                        CharacterName = formCollection["CMCharacterName"], 
                        Email = formCollection["CMEmail"]
                    }
                };

                db.Camps.Add(newCamp);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult Edit(int id)
        {
            if (!ValidateCredentials(PermissionConstants.EDIT_EXISTING_CAMPS))
            {
                return RedirectToAction("Index");
            }

            var camp = db.Camps.FirstOrDefault(c => c.CampId == id);
            if (camp == null)
            {
                return View("Error");
            }

            return View(new CampViewModel(camp));
        }

        [HttpPost]
        public ActionResult Edit(FormCollection formCollection)
        {
            if (!ValidateCredentials(PermissionConstants.EDIT_EXISTING_CAMPS))
            {
                return RedirectToAction("Index");
            }

            try
            {
                var userId = GetCurrentUserId();

                int existingCampId = Convert.ToInt32(formCollection["CampId"]);
                Camp camp = db.Camps.FirstOrDefault(c => c.CampId == existingCampId);
                if (camp == null)
                {
                    return View("Error");
                }

                camp.Name = formCollection["Name"];
                camp.Location = formCollection["Location"];
                camp.Year = Convert.ToInt16(formCollection["Year"]);
                camp.CampMaster.FirstName = formCollection["CMFirstName"];
                camp.CampMaster.LastName = formCollection["CMLastName"];
                camp.CampMaster.CharacterName = formCollection["CMCharacterName"];
                camp.CampMaster.Email = formCollection["CMEmail"];

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int campId)
        {
            if (!ValidateCredentials(PermissionConstants.DELETE_CAMPS))
            {
                return RedirectToAction("Index");
            }

            Camp camp = db.Camps.FirstOrDefault(c => c.CampId == campId);
            if (User != null)
            {
                db.Camps.Remove(camp);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult GenerateNumbers()
        {
            if (!ValidateCredentials(PermissionConstants.VIEW_CAMP_ADMINISTRATION))
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            var camps = db.Camps.Where(c => c.Year == YearConstants.CURRENT_EVENT_YEAR).Select(camp => new CampViewModel
            {
                CampId = camp.CampId,
                CampMasterId = camp.CampMasterId,
                Name = camp.Name,
                Location = camp.Location,
                Year = camp.Year.ToString(),
                CMCharacterName = camp.CampMaster.CharacterName,
                NumRegistrations = camp.Participants.Where(p => p.Status == "Paid" || p.Status == "Checked In").Count()
            }).OrderBy(c => c.Name).ToList();

            return View(camps);
        }
    }
}

RagnarokWebsite/Areas/Administration/Views/Camps/Create.cshtml
@model RagnarokWebsite.Models.CampViewModel

@{
    /**/

    ViewBag.Title = "Ragnarok > Camp Administration - Add New Camp";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12"><h2>Camp Administration - Add New Camp</h2></div>
</div>


@using (Html.BeginForm())
{
    <div class="row">
        @Html.AntiForgeryToken()

        <div class="col-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Location</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "" } })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Year</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.DropDownListFor(model => Model.Year, Model.Options)
        </div>
    </div>

    <div class="row">
        <div class="col-12 pt-2">
            <h3>Camp Master Information</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">First Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMFirstName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMFirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Last Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMLastName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMLastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Character Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMCharacterName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMCharacterName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Email</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMEmail, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-12 pt-2">
            <input type="submit" value="Add Camp" class="btn btn-success centerButton" />
        </div>
    </div>
}

<div class="row">
    <div class="col-12 pb-2 pb-2">
        @Html.ActionLink("Back to Camps", "Index")
    </div>
</div>

RagnarokWebsite/Areas/Administration/Views/Camps/Edit.cshtml
@model RagnarokWebsite.Models.CampViewModel

@{
    /**/

    ViewBag.Title = "Ragnarok > Camp Administration - Edit Camp";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12"><h2>Camp Administration - Edit Camp</h2></div>
</div>


@using (Html.BeginForm())
{
    <div class="row">
        @Html.AntiForgeryToken()

        <div class="col-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CampId)
            @Html.HiddenFor(model => model.CampMasterId)
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Location</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "" } })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Year</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.DropDownListFor(model => Model.Year, Model.Options)
        </div>
    </div>

    <div class="row">
        <div class="col-12 pt-2">
            <h3>Camp Master Information</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">First Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMFirstName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMFirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Last Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMLastName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMLastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Character Name</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMCharacterName, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMCharacterName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2 col-xs-12 pt-2">
            <span class="col-form-label">Email</span>
        </div>
        <div class="col-md-10 col-xs-12 pt-2">
            @Html.EditorFor(model => model.CMEmail, new { htmlAttributes = new { @class = "" } })
            @Html.ValidationMessageFor(model => model.CMEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="col-12 pt-2">
            <input type="submit" value="Save" class="btn btn-success centerButton" />
        </div>
    </div>
}

<div class="row">
    <div class="col-12 pb-2 pb-2">
        @Html.ActionLink("Back to Camps", "Index")
    </div>
</div>

RagnarokWebsite/Areas/Administration/Views/Camps/GenerateNumbers.cshtml
@model IEnumerable<RagnarokWebsite.Models.CampViewModel>

@{
    /**/

    ViewBag.Title = "Ragnarok > Camp Administration - Generate Registration Numbers";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12"><h2>Camp Administration - Generate Registration Numbers</h2></div>
</div>

<div class="row">
    <div class="col-12">
        @foreach (var camp in Model)
        {
            @Html.DisplayFor(modelItem => camp.Name)@: &colon; @Html.DisplayFor(modelItem => camp.NumRegistrations)<br />
        }
    </div>
</div>

<div class="row">
    <div class="col-12 pb-2 pb-2">
        @Html.ActionLink("Back to Camps", "Index")
    </div>
</div>

RagnarokWebsite/Areas/Administration/Views/Camps/Index.cshtml
@model RagnarokWebsite.Models.CampsViewModel

@using PagedList.Mvc;
@using RagnarokWebsite.Security.Constants;

@{
    ViewBag.Title = "Ragnarok > Camp Administration";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-8 col-xs-12"><h1>Role Administration</h1></div>
    <div class="col-md-4 col-xs-12 right headerRight text-right">
        @if (CheckPermission(PermissionConstants.CREATE_NEW_CAMPS))
        {
            @Html.ActionLink("Add New Camp", "Create")
        }
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-xs-12 pb-2">
        @using (Html.BeginForm("Index", "Camps", FormMethod.Get))
        {
            @Html.HiddenFor(model => Model.Page)
            @Html.HiddenFor(model => Model.Year)
            @:Show 
            <select id="PageLength" name="PageLength" onchange="form.submit();">
                @if (Model.PageLength == 10)
                {
                    <option value="10" selected>10</option>
                }
                else
                {
                    <option value="10">10</option>
                }
                @if (Model.PageLength == 25)
                {
                    <option value="25" selected>25</option>
                }
                else
                {
                    <option value="25">25</option>
                }
                @if (Model.PageLength == 50)
                {
                    <option value="50" selected>50</option>
                }
                else
                {
                    <option value="50">50</option>
                }
                @if (Model.PageLength == 100)
                {
                    <option value="100" selected>100</option>
                }
                else
                {
                    <option value="100">100</option>
                }
            </select>@: entries
        }
    </div>
    <div class="col-md-6 col-xs-12 pb-2 text-right">
        @using (Html.BeginForm("Index", "Camps", FormMethod.Get))
        {
            @Html.HiddenFor(model => Model.Page)
            @Html.HiddenFor(model => Model.PageLength)
            @:Year: @Html.DropDownListFor(model => Model.Year, Model.Options, new { @onchange = @"form.submit();" })
        }
    </div>
</div>
<div class="row">
    <div class="col-12">
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Camp Master</th>
                    <th>Location</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var camp in Model.Camps)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => camp.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => camp.CampMaster.CharacterName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => camp.Location)
                        </td>
                        <td class="text-right">
                            @if (CheckPermission(PermissionConstants.EDIT_EXISTING_CAMPS))
                            {
                                @Html.ActionLink("Edit", "Edit", new { id = camp.CampId })
                            }
                            @if (CheckPermission(PermissionConstants.DELETE_CAMPS))
                            {
                                if (CheckPermission(PermissionConstants.EDIT_EXISTING_CAMPS))
                                {
                                    <span> | </span>
                                }

                                using (Html.BeginForm("Delete", "Camps", FormMethod.Post, new { @class = "btn-link deleteButton" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.Hidden("campId", camp.CampId)
                                    <input type="submit" class="btn-link" value="Delete" onclick="return confirm('Are you sure you wish to remove this camp?')" />
                                }
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-3 pt-2 pb-2">
        Showing @Model.Camps.FirstItemOnPage to @Model.Camps.LastItemOnPage of @Model.Camps.TotalItemCount Records
    </div>
    <div class="col-9 pt-2 pb-2 text-center">
        @Html.PagedListPager(Model.Camps, page => Url.Action("Index", new { page,
            PageLength = Model.PageLength,
            Year = Model.Year
        }), new PagedListRenderOptions { LinkToFirstPageFormat = "First", LinkToPreviousPageFormat = "Previous", LinkToNextPageFormat = "Next", LinkToLastPageFormat = "Last",
            DisplayLinkToFirstPage = PagedListDisplayMode.Always, DisplayLinkToPreviousPage = PagedListDisplayMode.Always, DisplayLinkToNextPage = PagedListDisplayMode.Always,
            DisplayLinkToLastPage = PagedListDisplayMode.Always, DisplayEllipsesWhenNotShowingAllPageNumbers = true, MaximumPageNumbersToDisplay = 10 })
    </div>
</div>